# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"DirectValueMeta": "00_core.ipynb",
         "DocumentedEnum": "00_core.ipynb",
         "noop": "00_core.ipynb",
         "Events": "01_callback.core.ipynb",
         "Callback": "01_callback.core.ipynb"}

modules = ["foundations.py",
           "callback/core.py"]

doc_url = "https://muellerzr.github.io/fastai_annotated/"

git_url = "https://github.com/muellerzr/fastai_annotated/tree/{branch}/"

def custom_doc_links(name): return None
